services:
  - type: web
    name: crypto-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run crypto_analyzer_fixed.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false 