[build]
builder = "python:3.11"

[deploy]
startCommand = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
envs = ["DEEPSEEK_API_KEY", "COINMARKETCAP_API_KEY", "OPENAI_API_KEY"]

[http]
port = 8501 